colorscheme sonokai 

:set noswapfile
:set smartindent
:set copyindent
:set preserveindent
:set cursorline
:set splitbelow
:set expandtab
:set foldenable
:set relativenumber
:set showmatch
:set hlsearch
:set ignorecase
:set cursorline
:set nobackup
:set incsearch
:set nowrap
:set noshowmode
:set nosplitright
:set swapfile
:set scrolloff=4
:set conceallevel=0
:set updatetime=100
:set mouse=a
:set clipboard=unnamed
:set backspace=indent,eol,start
